name: vulnerabilities scan workflow

on:
  push:
    branches:
#[0-9] matches any digit ; + allows for one or more of those digits
      - 'release/v[0-9]+.[0-9]+'
      
jobs:
  scan_repo:
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Print branch
        run: echo "Now scanning branch ${{ github.ref_name }}"
      - name: Scan repo with Trivy
        id: trivy_scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-results.txt'
          severity: 'LOW'
      - name: Slack Notification
        if: needs.scan_repo.steps.trivy_scan.outputs.vulnerabilities != '[]'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: 'test-submission'
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
          SLACK_TITLE: Scan failed by ${{ github.actor }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Upload Trivy report to Slack
        if: needs.scan_repo.steps.trivy_scan.outputs.vulnerabilities != '[]'
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'trivy-results.txt'
          initial_comment: 'upload of trivy report'
        continue-on-error: true
      - name: Terminate workflow in failure
        if: needs.scan_repo.steps.trivy_scan.outputs.vulnerabilities != '[]'
        run: exit 1
  build_push_docker:
    needs: scan_repo
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - id: docker_meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ghcr.io/sigstore/sample-honk
          tags: type=sha,format=long
      - name: Docker Login
        uses: docker/login-action@v3
        
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: buildpush
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
  sign_and_notify:
    needs: build_push_docker
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
      - name: Check installed
        run: cosign version
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Sign Docker Image
        run: |
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
          cosign sign --yes --key cosign.key ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ needs.build_push_docker.steps.buildpush.outputs.digest }}
          TAGS: ${{ needs.build_push_docker.steps.docker_meta.outputs.tags }}
      - name: Slack actions vulnerabilities not found
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: 'test-submission'
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE:  |
            *Name:* Wong Yi Lun
            *Matriculation Number:* A0158012R
            *Email:* e0036525@u.nus.edu
            *Git:* https://github.com/${{ github.repository }}
            *Image:* https://hub.docker.com/repository/docker/${{ secrets.DOCKER_USERNAME }}/my-app/
          SLACK_TITLE: Image built and signed
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
